title: Gerbel Cookbook
description: Collection of cooking recipes
theme: just-the-docs
color_scheme: dark

url: https://mhgerov.github.io/gerbel-cookbook

aux_links:
  Template Repository: https://github.com/mhgerov/gerbel-cookbook
